image:
  file: .gitpod.Dockerfile

tasks:
  - init: mvn clean
    command: mvn install
#  - command: mkdir -p /workspace/data && mongod --dbpath /workspace/data

ports:
- port: 8080
  onOpen: open-preview
- port: 5432
  onOpen: ignore

vscode:
  extensions:
  - pflannery.vscode-versionlens@0.24.0:FzMGwBqMxkIHqADhVK2e2Q==