image:
  file: .gitpod.Dockerfile

tasks:
  - command: >
      echo DATABASE_URL=$DATABASE_URL >> .env &&
      echo ANOUMAN_ADDRESS=$ANOUMAN_ADDRESS >> .env &&

ports:
- port: 8080
  onOpen: open-preview
- port: 5432
  onOpen: ignore

vscode:
  extensions:
  - pflannery.vscode-versionlens@0.24.0:FzMGwBqMxkIHqADhVK2e2Q==
  - vscjava.vscode-maven@0.19.1:BvBDxQECRYP8SiCZ8Csrsg==
