version: 2 # use CircleCI 2.0
jobs: 
  build: 
    
    working_directory: ~/anouman-app

    docker: 
      - image: circleci/openjdk:13-buster

    steps: 

      - checkout 

      - restore_cache: 
          key: anouman-app-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: anouman-app-{{ checksum "pom.xml" }}

      - run: mvn com.github.eirslett:frontend-maven-plugin:1.7.6:install-node-and-npm -DnodeVersion="v12.13.0"
      
      - run: mvn package
      
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
          
      - store_test_results:
          path: ~/test-results
          
      - store_artifacts:
          path: ~/test-results/junit 
            
